name: 'actions-test'
description: 'Run jest tests, add status and checks'
author: 'tangro'
inputs:
  command:
    description: 'The name of the npm script to call. Default is "test:ci"'
    default: 'test:ci'
runs:
  using: 'node12'
  main: 'dist/index.js'
